name: Render RFC Table
on:
  issues:
    types: [opened,edited,deleted,transferred,assigned,unassigned,labeled,unlabeled]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: render table
        run: ./render-table.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update RFC table in README
          title: Update RFC table in README
          branch: auto/update-rfc-table
